// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCxhZuzRcrBRGaqEqjQkll4q_ki-NwbC8',
    appId: '1:369881710183:android:686604079b963b1d255ec2',
    messagingSenderId: '369881710183',
    projectId: 'locallo-17fec',
    storageBucket: 'locallo-17fec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkXZbNCgvI-dzZCIO1LQNKLph1qt2BS6A',
    appId: '1:369881710183:ios:2a2e2abcfc9bf842255ec2',
    messagingSenderId: '369881710183',
    projectId: 'locallo-17fec',
    storageBucket: 'locallo-17fec.appspot.com',
    androidClientId: '369881710183-pr21j9ue2l7kdbshq52dqjq3pfdd79n6.apps.googleusercontent.com',
    iosClientId: '369881710183-vq0dleevcdchle5oeupda5opogrl5j83.apps.googleusercontent.com',
    iosBundleId: 'com.example.localLo',
  );
}
